# Smallest useful configuration: one server, one location, static files only.
server {
    listen 127.0.0.1:8090;
    server_name basic.local;

    root  ./www;
    index index.html;

    location / {
        methods GET;
    }
}
