# 'autoindex' appears twice in the same location block.
server {
    listen 127.0.0.1:8090;
    root   ./www;

    location / {
        methods   GET;
        autoindex off;
        autoindex on;
    }
}
