# 'upload_store' appears twice in the same location block.
server {
    listen 127.0.0.1:8090;
    root   ./www;

    location /upload {
        methods POST;
        upload_store ./www/uploads;
        upload_store ./www/files;
    }
}
